# markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# heading-style
MD003:
  style: atx

# ul-style
MD004:
  style: dash

# no-trailing-spaces
MD009:
  strict: true

# line-length
MD013: false

# no-duplicate-heading
MD024: false

# ol-prefix
MD029:
  style: ordered

# no-inline-html
MD033: false

# hr-style
MD035:
  style: ---

# no-alt-text
MD045: false

# code-fence-style
MD048:
  style: backtick

# emphasis-style
MD049:
  style: underscore

# strong-style
MD050:
  style: asterisk
